### ISSUE TITLE
모임 리스트 조회

### ISSUE THREAD

**Issue by a-ryang** [Z-P0P/ZPOP#5]
## ✔️Tasks
- [x] 가상테이블 View 추가
- [x] 쿼리스트링 없을 때
- [x] 검색
- [x] 검색어 화면에 출력
- [x] 첫 화면 요청시 모집 중인 모임만 보기로 바꾸기
- [x] 모집중 옵션
- [x] 성별 옵션 컬럼
- [x] 로딩 애니메이션
- [x] 날짜 변환 필요
- [x] 카테고리 CSS
- [x] innerHTML 수업코드로 수정하기
- [x] 지역 옵션 - desktop
- [x] 카테고리 옵션 - desktop
- [ ] 로딩 CSS 이슈
- [x] 모임이 없을 경우 view 구현

**Comment by a-ryang** [comment]
참고
<img width="368" alt="스크린샷 2022-12-15 오후 11 41 10" src="https://user-images.githubusercontent.com/105474635/207889338-aed6d24b-c2f7-4a92-bd1a-f043fc8243c2.png">

**Comment by a-ryang** [comment]
Vue 적용하면서 마지막도 해결
